// Static catalog of all channels available in the Channel Manager

export const CHANNEL_CATALOG = [
  // ── OTAs ──────────────────────────────────────────────────────────────────
  {
    id: 'viator',
    name: 'Viator',
    category: 'OTA',
    description: "World's largest tours & activities OTA, TripAdvisor-owned",
    sync_direction: 'two_way',
    hub_type: 'viator',
    default_commission: 0.20,
    color: '#FF6900',
    initials: 'VI',
    status: 'available',
  },
  {
    id: 'getyourguide',
    name: 'GetYourGuide',
    category: 'OTA',
    description: "Europe's leading experiences platform",
    sync_direction: 'two_way',
    hub_type: 'getyourguide',
    default_commission: 0.20,
    color: '#FF0000',
    initials: 'GG',
    status: 'available',
  },
  {
    id: 'klook',
    name: 'Klook',
    category: 'OTA',
    description: 'Leading OTA for Asian markets',
    sync_direction: 'two_way',
    hub_type: 'klook',
    default_commission: 0.20,
    color: '#FF5C8E',
    initials: 'KL',
    status: 'available',
  },
  {
    id: 'musement',
    name: 'Musement',
    category: 'OTA',
    description: 'TUI Group OTA, strong in Italy & Germany',
    sync_direction: 'two_way',
    hub_type: 'musement',
    default_commission: 0.18,
    color: '#6C63FF',
    initials: 'MU',
    status: 'available',
  },
  {
    id: 'airbnb_experiences',
    name: 'Airbnb Experiences',
    category: 'OTA',
    description: 'Activities on the Airbnb platform',
    sync_direction: 'inbound_only',
    hub_type: 'airbnb_experiences',
    default_commission: 0.20,
    color: '#FF5A5F',
    initials: 'AB',
    status: 'available',
  },
  {
    id: 'booking_experiences',
    name: 'Booking.com Experiences',
    category: 'OTA',
    description: 'Booking.com activities section',
    sync_direction: 'inbound_only',
    hub_type: 'booking_experiences',
    default_commission: 0.15,
    color: '#003580',
    initials: 'BK',
    status: 'available',
  },
  {
    id: 'expedia_experiences',
    name: 'Expedia Local Expert',
    category: 'OTA',
    description: "Expedia's tours & activities division",
    sync_direction: 'two_way',
    hub_type: 'expedia_experiences',
    default_commission: 0.20,
    color: '#FFC72C',
    initials: 'EX',
    status: 'available',
  },
  {
    id: 'tripadvisor',
    name: 'TripAdvisor Experiences',
    category: 'OTA',
    description: 'TripAdvisor activity listings',
    sync_direction: 'two_way',
    hub_type: 'tripadvisor',
    default_commission: 0.15,
    color: '#34E0A1',
    initials: 'TA',
    status: 'available',
  },
  {
    id: 'civitatis',
    name: 'Civitatis',
    category: 'OTA',
    description: 'Leading Spanish-speaking OTA',
    sync_direction: 'inbound_only',
    hub_type: 'civitatis',
    default_commission: 0.20,
    color: '#E63946',
    initials: 'CV',
    status: 'available',
  },
  {
    id: 'tiqets',
    name: 'Tiqets',
    category: 'OTA',
    description: 'Museum & attraction tickets',
    sync_direction: 'two_way',
    hub_type: 'tiqets',
    default_commission: 0.20,
    color: '#F4A261',
    initials: 'TQ',
    status: 'available',
  },
  {
    id: 'manawa',
    name: 'Manawa',
    category: 'OTA',
    description: 'Outdoor & adventure activities',
    sync_direction: 'two_way',
    hub_type: 'manawa',
    default_commission: 0.20,
    color: '#2A9D8F',
    initials: 'MW',
    status: 'available',
  },
  {
    id: 'veltra',
    name: 'VELTRA',
    category: 'OTA',
    description: 'Japan-focused OTA',
    sync_direction: 'inbound_only',
    hub_type: 'veltra',
    default_commission: 0.20,
    color: '#E76F51',
    initials: 'VL',
    status: 'coming_soon',
  },
  {
    id: 'headout',
    name: 'Headout',
    category: 'OTA',
    description: 'Last-minute experiences',
    sync_direction: 'inbound_only',
    hub_type: 'headout',
    default_commission: 0.10,
    color: '#8338EC',
    initials: 'HO',
    status: 'available',
  },
  {
    id: 'peek',
    name: 'Peek',
    category: 'OTA',
    description: 'North America focused OTA',
    sync_direction: 'inbound_only',
    hub_type: 'peek',
    default_commission: 0.20,
    color: '#3A86FF',
    initials: 'PK',
    status: 'coming_soon',
  },
  {
    id: 'ctrip',
    name: 'Ctrip / Trip.com',
    category: 'OTA',
    description: "China's largest travel platform",
    sync_direction: 'inbound_only',
    hub_type: 'ctrip',
    default_commission: 0.20,
    color: '#006AFF',
    initials: 'CT',
    status: 'coming_soon',
  },
  {
    id: 'rezdy_marketplace',
    name: 'Rezdy Marketplace',
    category: 'OTA',
    description: 'Australia & NZ focused marketplace',
    sync_direction: 'two_way',
    hub_type: 'rezdy_marketplace',
    default_commission: 0.15,
    color: '#FF6B6B',
    initials: 'RM',
    status: 'available',
  },

  // ── Booking Hubs ──────────────────────────────────────────────────────────
  {
    id: 'bokun',
    name: 'Bókun',
    category: 'Booking Hub',
    description: 'TripAdvisor-owned booking & channel manager',
    sync_direction: 'two_way',
    hub_type: 'bokun',
    default_commission: 0,
    color: '#1A56DB',
    initials: 'BK',
    status: 'available',
  },
  {
    id: 'fareharbor',
    name: 'FareHarbor',
    category: 'Booking Hub',
    description: 'Commission-free booking software',
    sync_direction: 'two_way',
    hub_type: 'fareharbor',
    default_commission: 0,
    color: '#0D9488',
    initials: 'FH',
    status: 'available',
  },
  {
    id: 'regiondo',
    name: 'Regiondo',
    category: 'Booking Hub',
    description: 'European booking & channel manager',
    sync_direction: 'two_way',
    hub_type: 'regiondo',
    default_commission: 0,
    color: '#7C3AED',
    initials: 'RG',
    status: 'available',
  },
  {
    id: 'rezdy',
    name: 'Rezdy',
    category: 'Booking Hub',
    description: 'Tour operator software & marketplace',
    sync_direction: 'two_way',
    hub_type: 'rezdy',
    default_commission: 0,
    color: '#DB2777',
    initials: 'RZ',
    status: 'available',
  },
  {
    id: 'checkfront',
    name: 'Checkfront',
    category: 'Booking Hub',
    description: 'Online booking & management platform',
    sync_direction: 'two_way',
    hub_type: 'checkfront',
    default_commission: 0,
    color: '#059669',
    initials: 'CF',
    status: 'available',
  },
  {
    id: 'xola',
    name: 'Xola',
    category: 'Booking Hub',
    description: 'Experience management platform',
    sync_direction: 'two_way',
    hub_type: 'xola',
    default_commission: 0,
    color: '#DC2626',
    initials: 'XO',
    status: 'coming_soon',
  },
  {
    id: 'trekksoft',
    name: 'TrekkSoft',
    category: 'Booking Hub',
    description: 'Tours & activities software',
    sync_direction: 'two_way',
    hub_type: 'trekksoft',
    default_commission: 0,
    color: '#2563EB',
    initials: 'TS',
    status: 'coming_soon',
  },
  {
    id: 'planyo',
    name: 'Planyo',
    category: 'Booking Hub',
    description: 'Universal online reservation system',
    sync_direction: 'two_way',
    hub_type: 'planyo',
    default_commission: 0,
    color: '#4F46E5',
    initials: 'PL',
    status: 'coming_soon',
  },

  // ── Local Partners ────────────────────────────────────────────────────────
  {
    id: 'hotel_partner',
    name: 'Hotel Partner',
    category: 'Local Partner',
    description: 'Local hotel reseller integration',
    sync_direction: 'outbound_only',
    hub_type: 'hotel_partner',
    default_commission: 0.10,
    color: '#B45309',
    initials: 'HP',
    status: 'available',
  },
  {
    id: 'tourist_board',
    name: 'DMO / Tourist Board',
    category: 'Local Partner',
    description: 'Destination marketing organization',
    sync_direction: 'outbound_only',
    hub_type: 'tourist_board',
    default_commission: 0,
    color: '#047857',
    initials: 'TB',
    status: 'available',
  },
  {
    id: 'local_agency',
    name: 'Local Agency',
    category: 'Local Partner',
    description: 'Local travel agency reseller',
    sync_direction: 'outbound_only',
    hub_type: 'local_agency',
    default_commission: 0.10,
    color: '#0369A1',
    initials: 'LA',
    status: 'available',
  },
  {
    id: 'resort_concierge',
    name: 'Resort Concierge',
    category: 'Local Partner',
    description: 'On-property concierge desk',
    sync_direction: 'outbound_only',
    hub_type: 'resort_concierge',
    default_commission: 0.10,
    color: '#7C2D12',
    initials: 'RC',
    status: 'available',
  },

  // ── Website & Direct ──────────────────────────────────────────────────────
  {
    id: 'direct_booking',
    name: 'Direct Booking Page',
    category: 'Website',
    description: 'Your own branded booking widget',
    sync_direction: 'two_way',
    hub_type: 'custom_api',
    default_commission: 0,
    color: '#1D4ED8',
    initials: 'DB',
    status: 'available',
  },
  {
    id: 'wordpress',
    name: 'WordPress Plugin',
    category: 'Website',
    description: 'Embed booking on your WordPress site',
    sync_direction: 'outbound_only',
    hub_type: 'custom_api',
    default_commission: 0,
    color: '#21759B',
    initials: 'WP',
    status: 'available',
  },
  {
    id: 'google_things_to_do',
    name: 'Google Things To Do',
    category: 'Website',
    description: 'Free Google listing for experiences',
    sync_direction: 'outbound_only',
    hub_type: 'custom_api',
    default_commission: 0,
    color: '#EA4335',
    initials: 'GG',
    status: 'coming_soon',
  },
  {
    id: 'facebook_shop',
    name: 'Facebook Shop',
    category: 'Website',
    description: 'Sell via your Facebook page',
    sync_direction: 'outbound_only',
    hub_type: 'custom_api',
    default_commission: 0,
    color: '#1877F2',
    initials: 'FB',
    status: 'coming_soon',
  },

  // ── Payment ───────────────────────────────────────────────────────────────
  {
    id: 'stripe',
    name: 'Stripe',
    category: 'Payment',
    description: 'Online card payments',
    sync_direction: 'two_way',
    hub_type: 'custom_api',
    default_commission: 0,
    color: '#635BFF',
    initials: 'ST',
    status: 'available',
  },
  {
    id: 'paypal',
    name: 'PayPal',
    category: 'Payment',
    description: 'PayPal checkout integration',
    sync_direction: 'inbound_only',
    hub_type: 'custom_api',
    default_commission: 0,
    color: '#003087',
    initials: 'PP',
    status: 'available',
  },
  {
    id: 'mollie',
    name: 'Mollie',
    category: 'Payment',
    description: 'European payment gateway',
    sync_direction: 'two_way',
    hub_type: 'custom_api',
    default_commission: 0,
    color: '#000000',
    initials: 'ML',
    status: 'available',
  },
];

export const CATEGORIES = ['All', 'OTA', 'Booking Hub', 'Local Partner', 'Website', 'Payment'];

export const SYNC_DIRECTION_LABELS = {
  two_way: 'Two-way',
  inbound_only: 'Inbound only',
  outbound_only: 'Outbound only',
  webhook_only: 'Two-way',
};